### ISSUE TITLE
Add an image to a blog entry

### ISSUE THREAD

**Issue by Klaudioz** [karngyan/karngyan.com#1]
**Is your feature request related to a problem? Please describe.**
Putting a folder in ./content/posts which images break the blog.

**Describe the solution you'd like**
I just would like to see how to add an image in any of the posts already created.

**Describe alternatives you've considered**
I have a hexo blog. Porting the .md was easy but the folder with the name of the post containing images failed.

Amazing job BTW

**Comment by karngyan** [comment]
Hey @Klaudioz 

You can upload your images folder in the `static` directory. For example

if your image is inside a folder called `images` named `sample.png`

```md
![Alt Text](/images/sample.png)
```

Or like this if you want to resize it:
```html
<img width="30%" src="/images/sample.png" alt="Alt Text"/>
```

I also pushed a sample here: https://template.karngyan.com/blog/dignatus-sorores

Thanks 😊

**Comment by Klaudioz** [comment]
Thank you. It worked perfectly.

Another similar question. Is it possible to load an image in the new `recent blogs` section ?

**Comment by karngyan** [comment]
If you're fine with tinkering with tailwindcss a bit, yeah it is possible. But the current template doesn't support it.

You can edit this [BlogCard.vue](https://github.com/karngyan/karngyan.com/blob/template/components/blog/BlogCard.vue) component to add an image directly from blog's markdown. 

Just letting you know the same component is used to render on blog page as well. So the images will be added there as well.

**Comment by Klaudioz** [comment]
Thanks for your explanation. I was a backend engineer, so probably it'd be difficult for me to do it. 

Also I just discovered that I can use `<!--more-->` to format better the posts !!

**Comment by karngyan** [comment]
Not an issue, I'll try to add that feature as soon as possible.

Yep. So Anything before `<!--more-->` is passed as description to the blog component.

If you want to spend some time on writing blogs in nuxt-content, check this out: [Writing Content](https://content.nuxtjs.org/writing)

**Comment by karngyan** [comment]
Hey @Klaudioz 

How does this look? Are you looking for something like this? 😛 

![image](https://user-images.githubusercontent.com/32811552/122484504-5af56900-cff2-11eb-8aaf-2eb4d958e5a5.png)

**Comment by Klaudioz** [comment]
It looks amazing !!. Thanks for your hard work.
