### ISSUE TITLE
Add plausible for analytics

### ISSUE THREAD

**Issue by Klaudioz** [karngyan/karngyan.com#2]
**Is your feature request related to a problem? Please describe.**
Google Analytics is evil.

**Describe the solution you'd like**
I followed this [guide](https://debbie.codes/blog/nuxt-analytics/). It looks easy to do but when I check the source of my website I can't see Plausible add it to my head

**Describe alternatives you've considered**
I didn't find more.

**Additional context**
This is what I did, after running `https://debbie.codes/blog/nuxt-analytics/`:

<img width="541" alt="Screen Shot 2021-06-18 at 2 57 51 PM" src="https://user-images.githubusercontent.com/632625/122600061-7aa98300-d02c-11eb-86c4-7b7291fba14d.png">
<img width="609" alt="Screen Shot 2021-06-18 at 2 57 38 PM" src="https://user-images.githubusercontent.com/632625/122600066-7e3d0a00-d02c-11eb-81b8-a6a533cb9149.png">

**Comment by karngyan** [comment]
Hey so if you'll have a look at the console, plausible is added but the script is merged with nuxt generated scripts so you can't see the tag in head. I'll be pushing plausible in a few minutes to the repo.

![image](https://user-images.githubusercontent.com/32811552/122609577-d7905200-d09b-11eb-95cd-4ab026b18fe8.png)

You'd also want to 

```js
export default async function ({ app, store, $config }) {
  app.$plausible.enableAutoPageviews()
...
}
```

**Comment by karngyan** [comment]
Hey @Klaudioz 

Added plausible support, I was just procrastinating on doing it. But look what you made me do 🤒 🤣 

https://analytics.lookatx.dev/template.karngyan.com

**Comment by Klaudioz** [comment]
Amazing!!. I wish you tons of visits 💪
