### ISSUE TITLE
Empty section addition

### ISSUE THREAD

**Issue by Klaudioz** [karngyan/karngyan.com#3]
**Is your feature request related to a problem? Please describe.**
I'd like to have an empty section to add new stuff from zero. It can be disabled by default.

**Describe the solution you'd like**
With simple code, anybody will be able to use it to create more sections as desired.

**Additional context**
On my [website](https://klaudioz.eth.link/) I was able to "duplicate" `buyMeACoffee` section to add one linked to my [Polywork](https://www.polywork.com/klaudioz) site, but it's out of my knowledge.

**Comment by karngyan** [comment]
Interesting. What would be the content on this new page? 
I am thinking about automating it from the config file, so just want to know. Also would consider whether it's worth it to automate it.

As for now, you can follow these steps to add a new empty page:

1. Nuxt's routes are based on directory names. So create a new directory in `pages` and an `index.vue` file in it.
    - You can copy paste the contents from any of the existing pages.
2. Make changes in `components/TheNavBar.vue` [here](https://github.com/karngyan/karngyan.com/blob/template/components/TheNavBar.vue#L15) and [here](https://github.com/karngyan/karngyan.com/blob/template/components/TheNavBar.vue#L67).

**Comment by Klaudioz** [comment]
I'd to add a page with the tech stack I'm using. You're listing your hardware in uses (which is almost identical to mine lol) and I'd like to add software and maybe my workflows.

**Comment by karngyan** [comment]
Nice. So a new page or may be a section on the same `uses` page makes sense?

Also what do you mean by workflows?

**Comment by Klaudioz** [comment]
Maybe mine explanation was poor. I'd like to have an empty page like uses or resume.
About workflows and stack I'd like to share something like [this](https://tkainrad.dev/posts/managing-my-personal-knowledge-base/)

**Comment by Klaudioz** [comment]
> Interesting. What would be the content on this new page?
> I am thinking about automating it from the config file, so just want to know. Also would consider whether it's worth it to automate it.
> 
> As for now, you can follow these steps to add a new empty page:
> 
> 1. Nuxt's routes are based on directory names. So create a new directory in `pages` and an `index.vue` file in it.
>    
>    * You can copy paste the contents from any of the existing pages.
> 2. Make changes in `components/TheNavBar.vue` [here](https://github.com/karngyan/karngyan.com/blob/template/components/TheNavBar.vue#L15) and [here](https://github.com/karngyan/karngyan.com/blob/template/components/TheNavBar.vue#L67).

Thanks for this explanation. After getting a lot of "Travoltas" 😅 it's necessary also to add the new section to the `karngyan.config.js` file.
